# Customized for RL4CO
_target_: rl4co.utils.trainer.RL4COTrainer

default_root_dir: ${paths.output_dir}

accelerator: "auto"
precision: "bf16-mixed"
matmul_precision: "high"
gradient_clip_val: 1.0

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

enable_progress_bar: true        # must be true if any progress bar is used
num_sanity_val_steps: 0          # set 0 if you don't actually have a val dataloader