defaults:
  - _self_
  - callbacks: default.yaml
  - hydra: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - model: default.yaml # TODO: Need to create a separate file and override it here
  - env: default.yaml # TODO: Need to create a separate file and override it here
  - experiment: tsp-stepwise-ppo.yaml
#  - experiment: base_v1.yaml


seed: 1111
mode: "test"
train: False # set False to skip model training
test: True
compile: False
#ckpt_path: /home/ethan/repo/rl4co/logs/train/runs/tsp20/am-tsp20/2025-09-08_22-47-11/checkpoints/last.ckpt
ckpt_path: /home/ethan/repo/rl4co/logs/train/runs/tsp20/ppo-tsp20/2025-09-08_21-51-28/checkpoints/epoch_005.ckpt
tags: ["dev"]