defaults:
  - _self_
  - callbacks: default.yaml
  - hydra: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - model: default.yaml # TODO: Need to create a separate file and override it here
  - env: default.yaml # TODO: Need to create a separate file and override it here
  - experiment: base_v1.yaml


seed: 1111
mode: "train"
train: True # set False to skip model training
test: True
compile: False
ckpt_path: null
tags: ["dev"]